
from .constants import (
    STARTED, AWAITING_EMAIL, AWAITING_VERIFICATION_CODE, VERIFIED,
    AWAITING_CASE, STAGE_1, AWAITING_ISSUES, STAGE_2,
    AWAITING_ASPECTS, STAGE_3
)

STATE_MAP = {
    'STARTED': STARTED,
    'AWAITING_EMAIL': AWAITING_EMAIL,
    'AWAITING_VERIFICATION_CODE': AWAITING_VERIFICATION_CODE,
    'VERIFIED': VERIFIED,
    'AWAITING_CASE': AWAITING_CASE,
    'STAGE_1': STAGE_1,
    'AWAITING_ISSUES': AWAITING_ISSUES,
    'STAGE_2': STAGE_2,
    'AWAITING_ASPECTS': AWAITING_ASPECTS,
    'STAGE_3': STAGE_3,
}